[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "flowchem-gui"
version = "0.0.1"
requires-python = ">=3.11"
dependencies = [
    "flowchem",
    "PySide6>=6.5",
    "PySide6-Fluent-Widgets>=1.11.2",
    "tomli-w>=1.0",
    "loguru>=0.7",
    "zeroconf>=0.149.7",
]

[project.optional-dependencies]
test = ["pytest"]

[project.gui-scripts]
flowchem-gui = "main:main"

[tool.setuptools]
py-modules = ["main"]
packages = ["app", "app.tabs"]
