[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "flowchem-qt"
version = "0.0.6"
requires-python = ">=3.11"
dependencies = [
    "flowchem",
    "PyQt5>=5.15.11",
    "PyQt-Fluent-Widgets>=1.11.2",
    "tomli-w>=1.0",
    "loguru>=0.7",
    "zeroconf>=0.149.7",
]

[project.optional-dependencies]
test = ["pytest"]

[project.gui-scripts]
flowchem-qt = "main:main"

[tool.setuptools]
py-modules = ["main"]
packages = ["app", "app.tabs", "resources", "resources.icons"]

[tool.setuptools.package-data]
"resources.icons" = ["*.ico", "*.svg"]
